services:
     - type: web
       name: my-online-market
       runtime: python
       branch: main
       buildCommand: npm install && npm run build
       startCommand: npm start
       envVars:
         - key: NODE_ENV
           value: production