# Generated by Django 5.2 on 2025-04-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_savat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='savat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Savat',
        ),
    ]
