# Generated by Django 5.2 on 2025-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_savat_savatmahsulot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='savat',
        ),
        migrations.AddField(
            model_name='product',
            name='is_has',
            field=models.BooleanField(default=True),
        ),
    ]
