# Generated by Django 5.2 on 2025-04-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_savat_product_is_has'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_has',
        ),
    ]
