# Generated by Django 5.1.6 on 2025-04-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_xabar'),
    ]

    operations = [
        migrations.AddField(
            model_name='xabar',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
