# Generated by Django 5.2 on 2025-04-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='media/default-profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
