# Generated by Django 5.2 on 2025-04-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_customuser_address_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='t_me',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
