# Generated by Django 5.1.6 on 2025-04-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_xabar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xabar',
            name='recipient',
        ),
        migrations.AddField(
            model_name='xabar',
            name='qabul',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
