# Generated by Django 5.1.6 on 2025-04-11 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_remove_xabar_recipient_xabar_qabul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabar',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yubor_xabar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='xabar',
            name='qabul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qabul_xabar', to=settings.AUTH_USER_MODEL),
        ),
    ]
