# Generated by Django 5.1.6 on 2025-04-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_alter_xabar_author_alter_xabar_qabul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xabar',
            old_name='desc',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='xabar',
            name='is_view',
        ),
        migrations.AlterField(
            model_name='xabar',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='xabar',
            name='qabul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
