# Generated by Django 5.1.6 on 2025-04-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_rename_desc_xabar_text_remove_xabar_is_view_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xabar',
            old_name='text',
            new_name='desc',
        ),
    ]
