# Generated by Django 5.1.6 on 2025-04-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_rename_text_xabar_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='xabar',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
