# Generated by Django 5.1.6 on 2025-04-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0011_xabar_is_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xabar',
            old_name='qabul',
            new_name='receiver',
        ),
    ]
