# Generated by Django 5.1.6 on 2025-04-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0013_rename_xabar_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(blank=True, default='media/default-profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
